### ISSUE TITLE
Creating task when no project exists crashes

### ISSUE THREAD

**Issue by saward** [ajaxray/geek-life#1] opened 2020-06-14 06:34 UTC
Just tried this out, and when I tried creating a new task without first creating a project, it crashes.  Presumably because projectPane.activeProject is nil?

**Comment by ajaxray** [comment] 2020-06-14 07:37
Thanks for reporting. 👍 
Fixing it soon - should be resolved by next release.

**Closed** 2020-06-16 20:31 UTC
Labels: bug

**Comment by ajaxray** [comment] 2020-06-16 20:32
Hello @saward ,
The issue is fixed. Now, even the "New Task" input will not be visible without active project.
Can you please check and confirm?
